{
	"data": "ENC[AES256_GCM,data:a0oHmJDf2Ifgc9V/RdCqEk0KiC9onF/4XxIfhAyWFqEtcF6QqbuJWuSfc4BA7LkP+iTprCpJTAkN,iv:DLUx3ho/Ixe+xfLQNW+RCZnoc/UWTNpvGr+bbomK7Po=,tag:4p4+Uv5XJ4tyoZ3nkj3mHA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1dvxpflzv7pstnm3mrg2y85vx7zyr73e7xelr8jg4cfv8ayehxqdsrf49v0",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRFF3SlQxWDI4TWthelFP\nTFFneURlL0FWdXp5OFkxSWNJaWVxU2lZNDI0Ci92Y3BKby9PcEpRbVk5UDExTXlq\naXZhRFgzZytsVGpGeGZWaEJycFhmem8KLS0tIEkrY1JKZ1A3WXBzQldzQmJCcWFK\najRDbDFEb3EvbVRHSHlMM3BWU1BkVkEKl6YeZewWdHcchqWmu8XGBPnX5ZDPo9nF\nFstog2GiGUd+o1tsMR9gZ8Yivddl37XWVlYuJsXbxjkFEGEdNkbLZg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-02-13T14:34:00Z",
		"mac": "ENC[AES256_GCM,data:kPlTD87sKY8Oh3dLzRAZjsLkiX4WYIYIIgJvWxIql+Xd7RaE6yErzv/tH8KNUH0cI66Ot2VDzcUpGDhL6B9ZYUKIb+O/pSS0ljihmKY8ct9G2Xay2ObKQwK5moeFOPZMs5u7wbxAgchGCGRNI+jNCRG/2keNIydE3KaN3tUKxTU=,iv:DJOZAAEXqRBNtkXwYHOm7YFvOqtk/PogrdQXWhHKMig=,tag:C0P//7AInQVDg6wsl4dGUQ==,type:str]",
		"version": "3.11.0"
	}
}
