work_git_config: ENC[AES256_GCM,data:IV+lED7BVp2BVjuglIalY4dQEeCGqg52itJnB1uP0N6N6jd7vhV/hOwVtFS8XWNWOwC3OffVtaenTg==,iv:eGMrSU8NpblN+BiV2jYaHFFqMMKRw/MOhgIPZIJgrK8=,tag:+5a9fb4PZve3dSi2x5NL2A==,type:str]
sops:
    age:
        - recipient: age1dvxpflzv7pstnm3mrg2y85vx7zyr73e7xelr8jg4cfv8ayehxqdsrf49v0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RUNGR2h6SHRBdktLR0o5
            Y1dXd3YxNCt2ZlRvdHZ2VURIL3FUZndETWhVClExR3lDWXEvNmdkR0FWRGJxZ25a
            Wjdxb3dBRXl4NmZMZm0vQzdxbjVtdGsKLS0tIGxEejZDN044VDlQeVE2T1FuNjlw
            RVRsYXJ0NGlHQUhWU0I4Tkt4Q3FiVVUKE9WIXzjXVJrMztO9eiVTPwuek1OsOtzD
            Z7o9OwH2aAhotKPOF99RyBDA6/QuSTsSS2ovPUQ0cct8dmB4/g7lnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T14:43:01Z"
    mac: ENC[AES256_GCM,data:cu7JZCLmv2CV/fWL6cSDPp9itpwKfbHiAf91TX4MWs4qIjP88Fc70QSJK8H+QnAo17eQtfhybsttUyY95S4Q2x35BKwpv3ZrE41SIf8cBChQcZvFmlYHHOu0jZvOS9eou6HhwzTRHElteiP/DKhsXqcvHrAkKsK1ABrXqjTVg0M=,iv:dT89v6j38unIKF/MdmwQ7Rg8PPW63ok21cm4Q8oEvsQ=,tag:E5g/3WPLiQDNRqI+8Sht/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
